# NUMPY

#supports creation and manipulation of ndimensional homogenious arrays

homogenous arrays ==set of values of similar datatupe represendation

every array creation in numpy array is a class of nd array class object


homogenous arrays == set of values of multi fatatype represendation



why not list??
its a hetrogeneous methods

its not capable of handle large data set

numpy/standard python seq
1.numpy arrats have a fixed size at creation,unlike python list 

2.when changing array it will manipulate the originol data type

3.object -a classs instantce

4.numpy is used most in math and sci 

5.nd array will operate over elemnt by element

6.fullu supports object oriented approach

7.numpy dimensions are called axes










In [6]:
#to call numpy library



import numpy as np

dir(np)
a =np.array([1,2,3,4])
a
a1 =np.array([1,2,3,4],ndmin =2)
a1

array([[1, 2, 3, 4]])

In [8]:
#Dtype =data type

a3 =np.array([1,2,3,4],dtype =complex)
a3

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

# NUMPY DATA TYPE

In [10]:
b =np.dtype(np.int32)
b

dtype('int32')

In [12]:
b =np.dtype(np.int64)
b

dtype('int64')

# STRUCTURED DATA TYPES

In [26]:
#BASCI ARRAY CREATION

#format  = np.range(start,end,step,dtype)


a =np.arange(1,20,1,int)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
#to change the step value

a =np.arange(1,20,4,int)
a

array([ 1,  5,  9, 13, 17])

In [37]:
#MATRIX METHOD -shape & ndim

#.shape(row,coloumns)

#size-gives the size of the elements


#shape - it will take one or more integers into tuple form


a =np.arange(1,21,)
print(a)
a.shape =(4,5)
print(a)
print(a.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20


# ARAAY CREAATION USING np.array

1.allows list of values





In [42]:
a = np.array([1,2,3,4,5])
print(a)

#TOCHANGE THE DTYPE

a = np.array([1,2,3,4,5],dtype =complex)
print(a)


[1 2 3 4 5]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [47]:
#doble dimension array -matrix is a doble dimension array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)





[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
#reshape-function used to convert single dimension array to double dimension array

a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array creation using ZEROS 




it will take only singe values as a input

single list or single tuple



In [50]:
np.zeros(3)

array([0., 0., 0.])

In [53]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Arrays creation using ONES

In [54]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# arrays cration using random values()



empty-function used to create random numbers

In [62]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

# Copying an array into another
1)  -  Using assignment operator
2)  -  Shallow copy
3)  -  Deep copy


# Using assignment operator

it creates a refernce of originol copy

symbol is =

it doesnt create another copy of the array in the memory


In [66]:
a = np.array([1,2,3,4,5])
print(id(a))
b = a
print(id(b))
b[2] =7
print(b)
print(a)

2352062692688
2352062692688
[1 2 7 4 5]
[1 2 7 4 5]


# USING SHALLOW COPY

In [67]:
#view -function used for this 

a = np.array([1,2,3,4,5])
print(id(a))
print(a)
b = a.view
print(b)
print(id(b))



2352061073712
[1 2 3 4 5]
<built-in method view of numpy.ndarray object at 0x00000223A1C3C930>
2352016567808


# #Using DEEP Copy

In [68]:
a = np.array([1,2,3,4,5])
print(id(a))
print(a)
b = a.copy
print(b)
print(id(b))


2352062691056
[1 2 3 4 5]
<built-in method copy of numpy.ndarray object at 0x00000223A1DC76F0>
2352067695376


# ACCESSING array and to find the position of a element

#where -role searching


syntax: numpy.where(array_name==element_to_search)





In [69]:
a = np.array([1,2,3,4,5])
np.where(a==3)

(array([2], dtype=int64),)

In [70]:
#only for odd elements
a = np.array([1,2,3,4,5])
np.where(a%2==1)

(array([0, 2, 4], dtype=int64),)

In [71]:
#Binary search

#searchsorted-used for binry search





a = np.array([1,2,3,4,5])
np.searchsorted(a,4)


3

# MANIPULATE the arrays created using numpy


both arrrays must be same shape



In [75]:
#ADDDITIN


c =np.array([1,2,3,4]).reshape(2,2)
d =np.array([6,7,8,9]).reshape(2,2)
print(c)
print(d)
e =c + d
print(e)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 7  9]
 [11 13]]


In [76]:
#SUBRACTION


c =np.array([1,2,3,4]).reshape(2,2)
d =np.array([6,7,8,9]).reshape(2,2)
print(c)
print(d)
e =c - d
print(e)


[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[-5 -5]
 [-5 -5]]


In [81]:
#MULTIPLICATION

c =np.array([1,2,3,4]).reshape(2,2)
d =np.array([6,7,8,9]).reshape(2,2)
print(c)
print(d)
e =c * d
print(e)


#BUT as per matrix multiplication this ans is wrong

c =np.array([1,2,3,4]).reshape(2,2)
d =np.array([6,7,8,9]).reshape(2,2)
e =c @ d
print(e)


#@-operator  .product multiplication or we can use dot function
c =np.array([1,2,3,4]).reshape(2,2)
d =np.array([6,7,8,9]).reshape(2,2)
e =c.dot(d)
print(e)



[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 6 14]
 [24 36]]
[[22 25]
 [50 57]]
[[22 25]
 [50 57]]


In [83]:
#cmpound assignment operators
+= add every elemenr

*= mulitiply


c =np.array([1,2,3,4]).reshape(2,2)
print(c)
c+=5
print(c)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [84]:
#we can use that for multipliers also

c =np.array([1,2,3,4]).reshape(2,2)
print(c)
d =np.array([6,7,8,9]).reshape(2,2)
c+=d
print(c)

[[1 2]
 [3 4]]
[[ 7  9]
 [11 13]]
